# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lanelist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elanelist.proto\"\x1a\n\x02Pt\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\x8b\x01\n\x04Line\x12\x11\n\tlane_type\x18\x01 \x01(\x05\x12\x17\n\x0fpts_vehicle_num\x18\x02 \x01(\x05\x12\x18\n\x0bpts_vehicle\x18\x03 \x03(\x0b\x32\x03.Pt\x12\x13\n\x0bpts_abs_num\x18\x04 \x01(\x05\x12\x14\n\x07pts_abs\x18\x05 \x03(\x0b\x32\x03.Pt\x12\x12\n\nconfidence\x18\x06 \x01(\x01\"H\n\x08LaneList\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08lane_num\x18\x02 \x01(\x05\x12\x17\n\x08laneline\x18\x03 \x03(\x0b\x32\x05.Lineb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lanelist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PT._serialized_start=18
  _PT._serialized_end=44
  _LINE._serialized_start=47
  _LINE._serialized_end=186
  _LANELIST._serialized_start=188
  _LANELIST._serialized_end=260
# @@protoc_insertion_point(module_scope)
