# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"\x8d\x04\n\x08Location\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0e\n\x06height\x18\x04 \x01(\x01\x12\r\n\x05pitch\x18\x05 \x01(\x01\x12\x0c\n\x04roll\x18\x06 \x01(\x01\x12\x0f\n\x07heading\x18\x07 \x01(\x01\x12\x17\n\x0flinear_velocity\x18\x08 \x01(\x01\x12\x12\n\nvelocity_x\x18\t \x01(\x01\x12\x12\n\nvelocity_y\x18\n \x01(\x01\x12\x12\n\nvelocity_z\x18\x0b \x01(\x01\x12\x1b\n\x13linear_acceleration\x18\x0c \x01(\x01\x12\x16\n\x0e\x61\x63\x63\x65leration_x\x18\r \x01(\x01\x12\x16\n\x0e\x61\x63\x63\x65leration_y\x18\x0e \x01(\x01\x12\x16\n\x0e\x61\x63\x63\x65leration_z\x18\x0f \x01(\x01\x12\x18\n\x10\x61ngular_velocity\x18\x10 \x01(\x01\x12\x1a\n\x12\x61ngular_velocity_x\x18\x11 \x01(\x01\x12\x1a\n\x12\x61ngular_velocity_y\x18\x12 \x01(\x01\x12\x1a\n\x12\x61ngular_velocity_z\x18\x13 \x01(\x01\x12\x12\n\norigin_lon\x18\x14 \x01(\x01\x12\x12\n\norigin_lat\x18\x15 \x01(\x01\x12\x16\n\x0eutm_position_x\x18\x16 \x01(\x01\x12\x16\n\x0eutm_position_y\x18\x17 \x01(\x01\x12\x16\n\x0eutm_position_z\x18\x18 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATION._serialized_start=19
  _LOCATION._serialized_end=544
# @@protoc_insertion_point(module_scope)
