# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mmobstacles.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mmobstacles.proto\"\xde\x03\n\x08Obstacle\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1c\n\x14\x63\x65nter_pos_vehicle_x\x18\x02 \x01(\x01\x12\x1c\n\x14\x63\x65nter_pos_vehicle_y\x18\x03 \x01(\x01\x12\x1c\n\x14\x63\x65nter_pos_vehicle_z\x18\x04 \x01(\x01\x12\x18\n\x10\x63\x65nter_pos_abs_x\x18\x05 \x01(\x01\x12\x18\n\x10\x63\x65nter_pos_abs_y\x18\x06 \x01(\x01\x12\x18\n\x10\x63\x65nter_pos_abs_z\x18\x07 \x01(\x01\x12\x18\n\x10velocity_vehicle\x18\x08 \x01(\x01\x12\x14\n\x0cvelocity_abs\x18\t \x01(\x01\x12\x15\n\rtheta_vehicle\x18\n \x01(\x01\x12\x11\n\ttheta_abs\x18\x0b \x01(\x01\x12\x0e\n\x06length\x18\x0c \x01(\x01\x12\r\n\x05width\x18\r \x01(\x01\x12\x0e\n\x06height\x18\x0e \x01(\x01\x12\x0c\n\x04type\x18\x0f \x01(\x05\x12\x12\n\nconfidence\x18\x10 \x01(\x01\x12\x15\n\rlane_position\x18\x11 \x01(\x05\x12\x13\n\x0b\x66usion_type\x18\x12 \x01(\x05\x12\x10\n\x08\x63ross_id\x18\x13 \x01(\x05\x12\x10\n\x08src_type\x18\x14 \x01(\x05\x12\x0f\n\x07lane_id\x18\x15 \x01(\x05\x12\x12\n\nlane_index\x18\x16 \x01(\t\"T\n\x0bMMobstacles\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x14\n\x0cobstacle_num\x18\x02 \x01(\x05\x12\x1c\n\tobstacles\x18\x03 \x03(\x0b\x32\t.Obstacleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmobstacles_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSTACLE._serialized_start=22
  _OBSTACLE._serialized_end=500
  _MMOBSTACLES._serialized_start=502
  _MMOBSTACLES._serialized_end=586
# @@protoc_insertion_point(module_scope)
