# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trafficlightlist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16trafficlightlist.proto\"y\n\rTraffic_Light\x12\r\n\x05\x63olor\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x12\n\nlight_pt_x\x18\x03 \x01(\x05\x12\x12\n\nlight_pt_y\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\r\n\x05width\x18\x06 \x01(\x05\"g\n\x10TrafficLightlist\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x19\n\x11traffic_light_num\x18\x02 \x01(\x05\x12%\n\rtrafficlights\x18\x03 \x03(\x0b\x32\x0e.Traffic_Lightb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trafficlightlist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAFFIC_LIGHT._serialized_start=26
  _TRAFFIC_LIGHT._serialized_end=147
  _TRAFFICLIGHTLIST._serialized_start=149
  _TRAFFICLIGHTLIST._serialized_end=252
# @@protoc_insertion_point(module_scope)
